services:
  intent_recognition:
    command: --intent-graph /profiles/en/intent_graph.pickle.gz --examples /profiles/en/intent_examples.db
      --debug --host mosquitto --port 1883 --site-id default --confidence-threshold
      0 --replace-numbers --language en_US --casing lower --converters-dir /profiles/en/converters
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-fuzzywuzzy-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  microphone:
    command: --sample-rate 16000 --sample-width 2 --channels 1 --record-command 'arecord
      -q -r 16000 -f S16_LE -c 1 -t raw' --list-command 'arecord -L' --test-command
      'arecord -q -D {} -r 16000 -f S16_LE -c 1 -t raw' --debug --host mosquitto --port
      1883 --site-id default --udp-audio-host 127.0.0.1
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-microphone-cli-hermes
    tty: true
  speakers:
    command: --play-command 'aplay -q -t wav' --list-command 'aplay -L' --volume 1
      --debug --host mosquitto --port 1883 --site-id default
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-speakers-cli-hermes
    tty: true
  speech_to_text:
    command: --model /profiles/en/vosk/model --words-json /profiles/en/vosk/words.json
      --debug --host mosquitto --port 1883 --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-asr-vosk-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  text_to_speech:
    command: --tts-command 'nanotts -v {lang} -o {file}' --temporary-wav --text-on-stdin
      --volume 1 --debug --host mosquitto --port 1883 --site-id default --language
      en-US
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-tts-cli-hermes
    tty: true
  wake:
    command: --keyword porcupine.ppn --sensitivity 0.5 --keyword-dir /profiles/en/porcupine
      --debug --host mosquitto --port 1883 --site-id default
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-wake-porcupine-hermes
    tty: true
    volumes:
    - /profiles:/profiles
version: '2'
